#!/bin/bash -login 
#PBS -N hw2-jloop
#PBS -m a
#PBS -m b
#PBS -m e
#PBS -M zhangchunli.pku@gmail.com
#PBS -j oe
#PBS -l walltime=00:30:00
#PBS -l nodes=1:ppn=20
#PBS -l mem=750mb
######PBS -l file=100gb
######PBS -q debug
export OMP_NUM_THREADS=20
#####export KMP_STACKSIZE=256000000

cd $PBS_O_WORKDIR
module swap GNU Intel

./count_sort2 50000 20 &

wait
